### ISSUE TITLE
valet install issue

### ISSUE THREAD

**Issue by Wulfheart** [valeryan/valet-wsl#11]
`PHP Fatal error:  Cannot declare class Nginx, because the name is already in use in /home/alex/.composer/vendor/valeryan/valet-wsl/cli/includes/facades.php on line 32`

How can I fix this?

**Comment by valeryan** [comment]
I have not been able to replicate this issue. Maybe you can provide more details about how you set up valet and your environment.

**Comment by valeryan** [comment]
Closing until I hear back from @Wulfheart  that this is still an issue.
