### ISSUE TITLE
Wordpress Multsite Driver

### ISSUE THREAD

**Issue by aranwilcox** [valeryan/valet-wsl#12]
Hi, 

Was wondering if anyone has managed to get a Wordpress multisite setup working correctly using valet-wsl?

I can remember having the same issue when using Valet on a mac and I just needed to use a custom driver to get the URL's to work correctly. However, that custom driver doesn't seem to work on valet-wsl.

Many thanks

**Comment by aranwilcox** [comment]
Ok, I have figured out a workaround for the moment. I popped the driver into the root of the project and used it as a local driver instead.

**Comment by valeryan** [comment]
I don't know. I have not done much work with the drivers. The main focus of this project is making the modification to core systems to work with WSL. I occasionally go get fixes from the upstream project but I have not done that in a while.

**Comment by valeryan** [comment]
@aranwilcox I don't know if it helps your situation any but I pulled in all the fixes from upstream valet for Linux. I haven't really messed with the drivers cause I do laravel development and it always works. If it's still not working we can move this issue upstream and see if anyone else has resolved your issue.

**Comment by valeryan** [comment]
Closing because of no response.
