### ISSUE TITLE
Bug: WSL2 Issue with Acrylic DNS

### ISSUE THREAD

**Issue by marbuser** [valeryan/valet-wsl#14]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Ubuntu 18.04                | 7.4.2         | 1.0.5            |

- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-linux (`valet --version`): `<Valet-Linux-Version>`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
I was previously running on WSL 1 and everything was working fine. However, I recently upgraded to WSL 2. I know this doesn't have "official" support for WSL 2 yet, but in terms of Valet everything works fine. The issue appears to be with Acrylic DNS.

When editing my adapter settings, I now have 2 adapters instead of 1 as show below;
![image](https://user-images.githubusercontent.com/34422459/74245868-a9b83200-4d1e-11ea-9181-a36aae4a2b72.png)

I stuck to the first one just called `Ethernet` and changed my DNS settings to proxy through Acrylic, but the issue is it basically completely kills my internet.

When trying to access any `.test` domain it fails, and when trying to even access `www.google.com` I get the error `This site can't be reached`. As soon as I revert my adapter settings my internet comes back and it's working again (the `.test` domains still don't work obviously.)

My config and hosts file for Acrylic are completely stock except for the 1 change to add `127.0.0.1 *.test` to the hosts file.

Asking here in case anyone else has ran into this problem and been able to fix it somehow.

As a side note, now that we have a separate adapter for WSL 2, we might actually be able to get dnsmasq working and remove the need for Acrylic completely, but I'm not very experienced with networking so I could be wrong.

EDIT:
Although as a secondary thing I just checked, I uninstalled Acrylic and it appears even if I set the `.test` domain manually in my hosts file like so;
`127.0.0.1 my-doman.test`
It still doesn't work. If I go directly to `127.0.0.1` I get a `404 - Not Found` Valet page, but as soon as I try access `my-domain.test` I get the error `ERR_CONNECTION_REFUSED`. So no clue what's going on there? Just to make this more confusing, pinging the url from CMD gets a response.... So I literally have no idea what is going on now and I have no the faintest idea how to fix this. So hopefully someone can provide some input.

EDIT AGAIN:
I just tested downgrading to WSL 1 and followed the installation instructions exactly as they state on the WIki, as well setting my adapter settings and now I CAN load `google.com` and such, but when attempting to connect to any `.test` domain, I get the `refused to connect.` error.

So I'm a bit confused as to what the issue is. Perhaps this just doesn't play nice in general with the new Windows Insider Builds?

Either way though, I think it might be time to start looking into WSL 2. A majority of people I know doing dev work are already using 2 instead of 1 because of how much faster it is, and one of the major benefits of it is "Accessing network applications" which theoretically I *think* would make dnsmasq work as shown here;
https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes#accessing-network-applications

**Comment by valeryan** [comment]
https://github.com/valeryan/valet-wsl/issues/7

**Comment by valeryan** [comment]
https://github.com/valeryan/valet-wsl/issues/7#issuecomment-529243441

**Comment by valeryan** [comment]
Also, https://github.com/microsoft/WSL/issues/4592

**Comment by valeryan** [comment]
This is a known issue with WSL2 and Acrylic DNS conflict because of the network changes. dnsmasq and acrylic are both trying to bind port 53 for DNS resolution and the conflict cause acrylic to stop. You can work around this by turning of dnsmasq or configuring it to use an alternate port.

**Comment by rhonivanpareja** [comment]
> This is a known issue with WSL2 and Acrylic DNS conflict because of the network changes. dnsmasq and acrylic are both trying to bind port 53 for DNS resolution and the conflict cause acrylic to stop. You can work around this by turning of dnsmasq or configuring it to use an alternate port.

@valeryan how do i disable dnsmasq on wsl2?

**Comment by gech4me** [comment]
# How to use port forwarding instead of Acrylic DNS
## It works, `WSL V1` and `WSL V2`

@valeryan Please update the documentation with this procedure instead of Acrylic DNS.

Source: https://github.com/microsoft/WSL/issues/5606#issuecomment-660191974
<a href="https://ibb.co/5r17cxb"><img src="https://i.ibb.co/1r0S2JF/image.png" alt="image" border="0"></a>
Open an elevated PowerShell or cmd.exe prompt:

1. Type `ipconfig` and note the IP address for `Ethernet adapter vEthernet (WSL)`
2. To forward port `80` from localhost->WSL type:
```
netsh interface portproxy add v4tov4 listenport=80 listenaddress=127.0.0.1 connectport=80 connectaddress=<wsl_ip>
```
**Note:** it'd probably be wiser to use a different `listenport` just in case you actually want to run something on `80` within Windows at some point (i.e. 9080 such that you'd connect to http://localhost:9080). You might be scratching your head in the future as to why it doesn't work if you have that portproxy setup, but you had forgotten about it.

To see what portproxies you already have setup:

` netsh interface portproxy show all`

**Comment by mschnee** [comment]
Because this is the top result on Google for "Acrylic WSL2", this is an issue with WSL2 and has been reported [here: microsoft/WSL #4364](https://github.com/microsoft/WSL/issues/4364)
