### ISSUE TITLE
Bug: Running the install commands dependencies don't go any further

### ISSUE THREAD

**Issue by SHJordan** [valeryan/valet-wsl#16]
**Basic info**

| Windows 10 Build | WSL Distro      | WSL Verson  | PHP Version | Valet version |
| ---------------- | --------------- | ----------- | ------------| ------------- |
| Ex: 18363.657        | Ex: Ubuntu 18.4 | 1           | Not installed       | Not Installed         |

- [x] I've checked the issue queue and could not find anything similar to my bug.
- [ ] I'm on the latest version of valet-wsl (`valet --version`): `<Valet-wsl-Version>`
- [ ] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
Some dependencies are either missing or changed names.

**What was supposed to happen?**
Prepare WSL to install all needed php7+ stuff.

**What actually happened?**
![image](https://user-images.githubusercontent.com/884602/74952988-d1269300-53df-11ea-868f-dae9ca24ff76.png)

**How to reproduce this?**
Enable WSL->Download and install Ubuntu 18.04 WSL-> run step 6 of the installation guide: sudo apt-get install network-manager libnss3-tools jq xsel build-essential libssl-dev zip unzip dnsmasq nginx mysql-server php-fpm php-cli php-mysql php-sqlite3 php-intl php-zip php-xml php-curl php-mbstring redis-server php-redis php-pear php-dev pkg-config libz-dev libzip-dev libmemcached-dev libmemcached11 libmemcachedutil2 libmagickwand-dev imagemagick memcached

**What is the solution?**
Find the missing dependencies

**Comment by valeryan** [comment]
Did you run sudo apt update? Ubuntu package repository has to be refreshed before you can install packages.

**Comment by SHJordan** [comment]
I did. 
![image](https://user-images.githubusercontent.com/884602/74954178-7d1cae00-53e1-11ea-9465-53ec3c1c72dc.png)

**Comment by valeryan** [comment]
You are running Ubuntu 18.4 from the windows store?

**Comment by SHJordan** [comment]
I'm.
![image](https://user-images.githubusercontent.com/884602/74954580-14820100-53e2-11ea-9955-52c6cc0ec6e3.png)

**Comment by valeryan** [comment]
Hmm, I will attempt a fresh install to see what's changed.

**Comment by valeryan** [comment]
I completely removed my wsl install of ubuntu and started fresh. I had no issues with any of the steps in the install guide. 

Please provide the output of `lsb_release -a` in your ubuntu install so I can verify what is getting installed. Also, have you made any changes to your apt repositories or done dist upgrades?

**Comment by SHJordan** [comment]
Sure thing
![image](https://user-images.githubusercontent.com/884602/75001630-b6383b00-5440-11ea-84df-c1bbcd4800d3.png)

Only change was on sources.list to replace US with BR mirrors. found here
https://launchpad.net/ubuntu/+mirror/ubuntu.c3sl.ufpr.br-archive

**Comment by valeryan** [comment]
I was not able to replicate your problem on two separate installs of windows. Those packages are meta-packages that install a set of packages. The meta package may not exist in your localized mirror.

**Comment by SHJordan** [comment]
Ok! Will try again with another mirrors. Probably was a issue on my end it seems.

**Comment by valeryan** [comment]
Sorry I couldn't help more.
