### ISSUE TITLE
Setup xdebug+phpstorm on Valet WSL

### ISSUE THREAD

**Issue by mshdevtech** [valeryan/valet-wsl#5]
Hi! I'm going to use your modification of valet for my projects. Everything works pretty well on Drupal. But there are issues with debugging. Actually it not stops at breakpoints in project. Does anyone have similar issues? I didn't found any information related wsl xdebug and valet, so I hope someone can help here

**Comment by valeryan** [comment]
I don't currently use phpstorm and I typically don't use xdebug and instead use a more direct approach for debugging like inserting temporary calls to `var_dump` in my code. I will have to set up some stuff and maybe get back to you.

**Comment by maarten-v** [comment]
I got it working. I use Phpstorm for my projects and normally you point to the local php executable for debugging in the phpstorm settings. But you cannot choose the WSL php for that.
Someone created a program that you can choose as the php executable that forwards all communication to the WSL php executable. And then everything works. This is what I use for that: https://github.com/michal-kocarek/PhpOnWindows

**Comment by mshdevtech** [comment]
hi @maarten-v  basically I figured out the issue with configuring pointing of php in phpstorm.
I configured openssh in WSL and pointed it to phpstorm.
![Снимок](https://user-images.githubusercontent.com/1592916/61908810-3a712100-af39-11e9-9894-409c1dcec9c1.PNG)

I'm actually can run xdebug, but it stops on '/home/max/.composer/vendor/valeryan/valet-wsl/server.php' 

And I see this error in debug console (phpstorm):

`Remote file path '/home/max/.composer/vendor/valeryan/valet-wsl/server.php' is not mapped to any file path in project`

**Comment by mshdevtech** [comment]
Finally I figured out how to configure Valet WSL + xdebug + phpstorm + drupal! I suppose it will work on other projects too.

1.  Install and configure xdebug on your WSL server. I used next config in /etc/php/7.3/fpm/conf.d/20-xdebug.ini:
`zend_extension=xdebug.so`
`xdebug.remote_autostart=1`
`xdebug.default_enable=1`
`xdebug.remote_enable=1`
`xdebug.remote_host=127.0.0.1`
`xdebug.remote_port=9001 ; change port to 9001, because 9000 used by Valet itself`
`xdebug.remote_connect_back=1`
`xdebug.idekey=PHPSTORM`
1.1 Add host cgi parameter in valet nginx conf file (/etc/nginx/sites-enabled/valet.conf):
`fastcgi_param SERVER_NAME $host;`
2. Point php to your phpstorm (http://blog.spameri.cz/2017/04/20/phpstorm-wsl-php.html)
3. Clone valet-wsl somewhere in your local machine (e.g. C:/valet-wsl)
4. Add your valet-wsl folder to Include paths in phpstorm
![Снимок2](https://user-images.githubusercontent.com/1592916/61911825-3d700f80-af41-11e9-8f31-0b4b5c81fa6c.PNG)
5. Configure debug settings
![Снимок3](https://user-images.githubusercontent.com/1592916/61911847-537dd000-af41-11e9-9d98-f805f3e6f23b.PNG)
![Снимок4](https://user-images.githubusercontent.com/1592916/61911907-78724300-af41-11e9-9741-8834a7652720.PNG)
6. Make sure that your mappings in server config is correct:
![Снимо5](https://user-images.githubusercontent.com/1592916/61912304-65ac3e00-af42-11e9-99a7-35a47f07a6c4.PNG)

**Comment by valeryan** [comment]
Glad you got it worked out. Let me know if you need anything else.
