### ISSUE TITLE
Regarding your issue with mysql secure installation

### ISSUE THREAD

**Issue by moyvera** [valeryan/valet-wsl#6]
> I ran into some issues with MySql not having a password and not being able to get mysql_secure_installation to work. As a workaround I used mysqladmin....

I think the issue is... 

Run mysql with root user as root

`sudo mysql -u root`

and/or run 

`sudo mysql_secure_installation`

Everything for me is running normal without extra config

**Comment by valeryan** [comment]
My solution allows you to use mysql without sudo privileges. However, the issues I run into is that `sudo mysql_secure_installation` does not seem to update the password when I run it and my sql password still ends up being blank. However, the alternate method I mention gets around this.
