### ISSUE TITLE
Issue 404 not found when open url

### ISSUE THREAD

**Issue by jsonpreet** [valeryan/valet-wsl#8]
When i open valet link giving name with .test it show 404 not found! I tried to add index.php in /home/foldername/.valet/sites/foldername but still show 404 not found

**Comment by valeryan** [comment]
Make sure you have followed all steps from https://github.com/valeryan/valet-wsl/wiki/Installation-Guide.

Test that your url is being handled correctly by your dns

run `ping example.test`

You should see something like:

```
PING example.test (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.047 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.048 ms
64 bytes from localhost (127.0.0.1): icmp_seq=3 ttl=64 time=0.053 ms
64 bytes from localhost (127.0.0.1): icmp_seq=4 ttl=64 time=0.039 ms
^C
--- example.test ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 75ms
rtt min/avg/max/mdev = 0.039/0.046/0.053/0.009 ms
```

**Comment by valeryan** [comment]
@harpreet9629 I have not heard back from you. I just did a fresh setup on windows though so I went through the whole process listed above and I was able to get a site up and running using valet. 

check the output of `valet links` and make sure you are adding the index.php into the correct folder. 

I am going to close this until I hear back from you. 

Thanks.
